name: generateDocs

on:
  push:
    branches:
    - main

jobs:

  buildandgeneratepdf:
    name: setup,generateDocs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up dev environment
        run: >-
          pip install -e ".[dev]"
      - name: Build docker image for wkhtmtopdf
        run: >-
          docker build -f Dockerfile.dockerfile -t wkhtmtopdf-0.12.6 .
      - name: Generate pdoc documentation from source
        working-directory: ${{ github.workspace }}/submodule/aqua-blue
        run: >-
          pdoc -d google aqua_blue -o _build --math --logo "https://raw.githubusercontent.com/YourOrg/YourRepo/refs/heads/main/assets/blue.jpg" --favicon "https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f30a.png"
      - name: create html file
        run: >-
          python fullProcess.py
      - name: generate pdf file
        run: >-
          MSYS_NO_PATHCONV=1 docker run --rm -v $(pwd):/data wkhtmtopdf-0.12.6 wkhtmltopdf --enable-javascript --disable-smart-shrinking --no-stop-slow-scripts --debug-javascript --enable-local-file-access --print-media-type --javascript-delay 10000 --user-style-sheet myStyles.css "file:///data/combined.html" documentation.pdf
      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: documentation.pdf
      - name: Upload generated docs
        uses: actions/upload-artifact@v4
        with:
          name: combined-html
          path: combined.html
      - name: create temp directory
        run: >-
          mkdir outputDir
      - name: Move only the PDF to temp dir
        run: |
          cp documentation.pdf outputDir/
      - name: Create index file to point to pdf
        run: |
          echo '<!DOCTYPE html>
            <html>
              <head>
                <meta http-equiv="refresh" content="0; url=documentation.pdf" />
                <title>Redirecting to PDF</title>
              </head>
            <body>
            <p>If you are not redirected, <a href="documentation.pdf">click here</a>.</p>
            </body>
            </html>' > outputDir/index.html
      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./outputDir
          publish_branch: gh-pages
